### ISSUE TITLE
Command-line option to turn off emojis

### ISSUE THREAD

**Issue by womblep** [peterpeterparker/tsdoc-markdown#37]
It would be great to have a command line option to turn off emojis as I would like to remove them and I am having to post-process to do that.

Thanks
Russell

**Comment by peterpeterparker** [comment]
I just released a new version (v1.0.0 to align with semver) that introduces a new command-line option, `--noemoji`, which skips emojis in the titles.

**Comment by womblep** [comment]
thank you!!
