### ISSUE TITLE
JS private identifiers are included in the generated documentation

### ISSUE THREAD

**Issue by bryan-hoang** [peterpeterparker/tsdoc-markdown#45]
Documentation for private class methods defined using private identifier syntax (i.e., `#privateMethod() {}`) is always emitted, despite being private at runtime.

**To Reproduce**

See https://github.com/bryan-hoang/repro-tsdoc-markdown-private-identifiers

**Expected behavior**

I expected the documentation to be omitted, like how it is for private methods declared using the `private` keyword.

**Additional context**

To work around the issue, I have to switch to using the `private` keyword.

I took a quick glance at how the visibility for the documented symbol is determined in [`src/lib/docs.ts#146`](https://github.com/peterpeterparker/tsdoc-markdown/blob/952f9b19d2d4d01110ce7cfa5c7557d9626755b9/src/lib/docs.ts#L146). Based on Typescript AST Viewer [^1], checking for `PrivateIndentifier` seems to be the way to go, although I'm not familiar enough with the compiler's API to know how difficult it would be to add the check.

[^1]: https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAYwDYEMDOa4BlgBMDmwUAwigHYCWaMRcA3gFACQA9AFRvNxtwAKUFAG4oacCrmBkYFAGYVaAW2AwAFhFwA6LjwACYAcJraWzAMRo1AVyS4AchABCwACIQElpVLwAKAJT1mJgQIMjQIJGANJAh8bwByFWAkaLjfAG5mAF8GZnZOJm4+AxFgOCVVdS0C3X0hEuNmWsNSiwhrO0cXNw9JGlw-AKYgkLCIqJj4xOSIVIymbOygA

**Comment by peterpeterparker** [comment]
Good catch! The private identifier syntax was indeed being generated, and I also noticed that the inner properties of classes weren’t being generated either. I resolved both issues this evening and released a new version of the library, v1.1.0.

**Comment by bryan-hoang** [comment]
Thank you @peterpeterparker!
