### ISSUE TITLE
Support for interfaces / types

### ISSUE THREAD

**Issue by JulianCataldo** [peterpeterparker/tsdoc-markdown#6]
Hello,

Really cool project, I'm glad I found it. Thanks.

Just wondering if I missed something, as it outputs **Functions**, **Constants**, but not **Interfaces** and **Types**. Am I wrong?

Bye!

**Comment by peterpeterparker** [comment]
That's correct. The idea is to export/document only what the end developers can consume (kind of) - i.e. the idea is not to document everything but to stay concise.

I'll add a comment in the README, that's a good question. Thanks!

**Comment by gerbyzation** [comment]
I was looking for this as well, as I'd like the types for parameter and return values to be documented. The readme of this package itself runs into the same issue, where for example there are references to `MarkdownOptions`  but you have to dive into the source to see what this actually should look like as it's not included in the generated docs.

> See MarkdownOptions for details.

**Comment by peterpeterparker** [comment]
I have now added a "Limitation" chapter to the README: https://github.com/peterpeterparker/tsdoc-markdown#limitation

Happy to get a PR for this.

**Comment by peterpeterparker** [comment]
thanks for correcting the link!

**Comment by peterpeterparker** [comment]
It might be a bit rough around the edges, but I have now added support for generating documentation for interfaces and types as well. By default, these won't be generated; it's an opt-in feature that can be enabled with the build options `--types`.

You can check out the results in this repository 👉 https://github.com/junobuild/juno-js/tree/main/packages/config

It was released in version [v0.2.0](https://github.com/peterpeterparker/tsdoc-markdown/releases/tag/v0.2.0), with an additional small fix for the markdown in version [v0.2.1](https://github.com/peterpeterparker/tsdoc-markdown/releases/tag/v0.2.1).

Let me know if it needs improvements.
